image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8002
- port: 9001
- port: 15672

vscode:
  extensions:
    - TabNine.tabnine-vscode@3.1.11:TrOGC+uTC6k193ZaAykXBg==

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - name: "Services"
    command: service nginx start &
             cd /workspace/magento2gitpod && chmod a+rwx mysql-bashrc-launch.sh && ./mysql-bashrc-launch.sh &
             /usr/sbin/php-fpm7.3 --fpm-config php-fpm.conf &
             rm -f /etc/php/7.3/cli/conf.d/20-tideways.ini && rm -f /etc/php/7.3/fpm/conf.d/20-tideways.ini &&
             /opt/rabbitmq/sbin/rabbitmq-server &
             rabbitmq-plugins enable rabbitmq_management &
  - name: "Start Crons"
    command: echo "while true; do /usr/bin/php /workspace/magento2gitpod/bin/magento cron:run >> /workspace/magento2gitpod/var/log/cron.log && /usr/bin/php /workspace/magento2gitpod/update/cron.php >> /workspace/magento2gitpod/var/log/cron.log && /usr/bin/php /workspace/magento2gitpod/bin/magento setup:cron:run >> /workspace/magento2gitpod/var/log/cron.log; sleep 60; done"
  - openIn: left
    command: chmod a+rwx menu.sh && ./menu.sh
  - openMode: split-right
    command: echo SplitTerminal
  - openIn: main
    command: echo LeftPanelTerminal
