image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8002
- port: 9001
- port: 15672

vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - before: /sbin/cron -f -L8
  - openMode: tab-after
  - command: service nginx start &
  - openMode: tab-before
  - command: cd /workspace/magento2gitpod && chmod a+rwx mysql-bashrc-launch.sh && ./mysql-bashrc-launch.sh
  - openMode: tab-before
  - command: /usr/sbin/php-fpm7.3 --fpm-config php-fpm.conf &
  - openMode: tab-before
  - command: rm -f /etc/php/7.3/cli/conf.d/20-tideways.ini && rm -f /etc/php/7.3/fpm/conf.d/20-tideways.ini
  - openMode: tab-before
  - command: chmod a+rwx menu.sh && ./menu.sh
  - openMode: tab-before
  - command: /opt/rabbitmq/sbin/rabbitmq-server &
  - openMode: tab-before
  - command: rabbitmq-plugins enable rabbitmq_management
